version: '3.8'
services:
  db-pipeline:
    image: postgres:15-alpine
    container_name: taskflow-db-pipeline
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
      POSTGRES_DB: taskflow_db
    volumes:
      - postgres_data_pipeline:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - taskflow-pipeline-network

  backend-pipeline:
    image: pakarmy786/taskflow-backend:latest
    container_name: taskflow-backend-pipeline
    environment:
      DATABASE_URL: postgresql://taskflow:taskflow123@db-pipeline:5432/taskflow_db
      JWT_SECRET_KEY: 8f4e2b1c9d6a5e3f7b8c2d4e1a9f6b3c5d7e8a2b4c6d8e1f3a5b7c9d2e4f6a8b
    ports:
      - "8081:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - db-pipeline
    networks:
      - taskflow-pipeline-network

  frontend-pipeline:
    build: ./frontend  # Use Dockerfile to build, not pre-built image
    container_name: taskflow-frontend-pipeline
    environment:
      VITE_API_URL: http://15.223.243.107:8081
    ports:
      - "8082:3000"
    depends_on:
      - backend-pipeline
    networks:
      - taskflow-pipeline-network

volumes:
  postgres_data_pipeline:

networks:
  taskflow-pipeline-network:
    driver: bridge
